; Copyright © Microsoft Corp.

[Theme]
; Windows - IDS_THEME_DISPLAYNAME_AERO
DisplayName=computerRepairCentre10
ThemeId={4BBC8A01-133D-4332-9C01-9CF6BF5DE452}

; Computer - SHIDI_SERVER
[CLSID\{20D04FE0-3AEA-1069-A2D8-08002B30309D}\DefaultIcon]
DefaultValue=%SystemRoot%\System32\imageres.dll,-109

; UsersFiles - SHIDI_USERFILES
[CLSID\{59031A47-3F72-44A7-89C5-5595FE6B30EE}\DefaultIcon]
DefaultValue=%SystemRoot%\System32\imageres.dll,-123

; Network - SHIDI_MYNETWORK
[CLSID\{F02C1A0D-BE21-4350-88B0-7367FC96EF3C}\DefaultIcon]
DefaultValue=%SystemRoot%\System32\imageres.dll,-25

; Recycle Bin - SHIDI_RECYCLERFULL SHIDI_RECYCLER
[CLSID\{645FF040-5081-101B-9F08-00AA002F954E}\DefaultIcon]
Full=%SystemRoot%\System32\imageres.dll,-54
Empty=%SystemRoot%\System32\imageres.dll,-55

[Control Panel\Cursors]
AppStarting=%SystemRoot%\Cursors\El Capitan\Working.ani
Arrow=%SystemRoot%\Cursors\El Capitan\Normal.cur
Crosshair=%SystemRoot%\Cursors\El Capitan\Precision.cur
Hand=%SystemRoot%\Cursors\El Capitan\Link.cur
Help=%SystemRoot%\Cursors\El Capitan\Help.cur
IBeam=%SystemRoot%\Cursors\El Capitan\Text.cur
No=%SystemRoot%\Cursors\El Capitan\Unavailable.cur
NWPen=%SystemRoot%\Cursors\El Capitan\Handwriting.cur
SizeAll=%SystemRoot%\Cursors\El Capitan\Move.cur
SizeNESW=%SystemRoot%\Cursors\El Capitan\Diagonal Resize 2.cur
SizeNS=%SystemRoot%\Cursors\El Capitan\Vertical Resize.cur
SizeNWSE=%SystemRoot%\Cursors\El Capitan\Diagonal Resize 1.cur
SizeWE=%SystemRoot%\Cursors\El Capitan\Horizontal Resize.cur
UpArrow=%SystemRoot%\Cursors\El Capitan\Alternate.cur
Wait=%SystemRoot%\Cursors\El Capitan\Busy.ani
DefaultValue=El Capitan

[Control Panel\Desktop]
Wallpaper=%SystemDrive%\Computer Repair Centre\Wallpapers\2cRQltQ.jpeg
Pattern=
MultimonBackgrounds=0
PicturePosition=4

[VisualStyles]
Path=%SystemRoot%\resources\themes\Aero\Aero.msstyles
ColorStyle=NormalColor
Size=NormalSize
AutoColorization=0
ColorizationColor=0XC40078D7
VisualStyleVersion=10

[boot]
SCRNSAVE.EXE=

[MasterThemeSelector]
MTSM=RJSPBS

[Sounds]
; IDS_SCHEME_DEFAULT
SchemeName=@mmres.dll,-800

[Slideshow]
ImagesRootPIDL=WGAFA8BUg/E0gouOpBhoYjAArADMdmBAvMkOcBAAAAAAAAAAAAAAAAAAAAAAAAgdAEDAAAAAAwGTgGGEAM0TNBVVU5XMAAgXAkAAEAw7+OGT7CFbMBaYuAAAAcWvDAAAA8CAAAAAAAAAAAAAAAAAAAQnyzEADBwbA0GAwBQdAQHAlBgcAACASBQZAAHAhBQaAIHAgAwQAUGAuBAdAIHAlBAAAgBAxDQMAAAAAAAbMFaYQAwVBxETQFkfxAAAGBQCAQAAv7LbM1ZYsxUoh5CAAAwxTCAAAAgjAAAAAAAAAAAAAAAAAAAAP/l6AcFAhBAbAwGAwBQYAAHAlBgcAMHAAAAGAMJAAAwJA8uvFCAAAEzUQN1td66/Nyx/DFIjECkOjOXLpBAAAQGAAAAAfAAAAwCAAAwdAkGAuBAZA8GA3BwcA4CApBQbA0GAlBgcAMHApBgdAUGAjBwbA4GA0BgcA8GAsBAcAEGAuBQZAwGAfBwYAcHA1AgbAEDAoBgMAQHA4BQeAUGA3BQeAAAAAAAAAAAAAAAGAAAA

Interval=1800000
Shuffle=1
